// This file will be auto-generated by kysely-codegen
// Run: bun run kysely:generate

export interface DB {
  users: UsersTable;
  sessions: SessionsTable;
  accounts: AccountsTable;
  students: StudentsTable;
  parent_students: ParentStudentsTable;
  topics: TopicsTable;
  topic_prerequisites: TopicPrerequisitesTable;
  topic_encompassing: TopicEncompassingTable;
  knowledge_points: KnowledgePointsTable;
  items: ItemsTable;
  student_topic_states: StudentTopicStatesTable;
  evidence_events: EvidenceEventsTable;
  student_stats: StudentStatsTable;
}

interface UsersTable {
  id: string;
  email: string;
  name: string;
  role: "student" | "parent" | "coach" | "admin";
  profile_id: string | null;
  created_at: Date;
  updated_at: Date;
}

interface SessionsTable {
  id: string;
  user_id: string;
  expires_at: Date;
  created_at: Date;
}

interface AccountsTable {
  id: string;
  user_id: string;
  provider: string;
  provider_account_id: string;
  refresh_token: string | null;
  access_token: string | null;
  expires_at: Date | null;
  created_at: Date;
}

interface StudentsTable {
  id: string;
  user_id: string | null;
  name: string;
  grade: string;
  birth_date: Date | null;
  motivation_profile: any;
  settings: any;
  created_at: Date;
  updated_at: Date;
}

interface ParentStudentsTable {
  parent_id: string;
  student_id: string;
}

interface TopicsTable {
  id: string;
  title: string;
  domain: "math" | "reading";
  strand: string;
  grade_band: "PreK" | "K" | "1";
  description: string | null;
  interference_group: string | null;
  expected_time_seconds: number;
  check_chart_tags: any;
  assets: any;
  created_at: Date;
  updated_at: Date;
}

interface TopicPrerequisitesTable {
  topic_id: string;
  prerequisite_id: string;
  gate: string;
}

interface TopicEncompassingTable {
  child_topic_id: string;
  parent_topic_id: string;
  weight: number;
}

interface KnowledgePointsTable {
  id: string;
  topic_id: string;
  objective: string;
  worked_example: any;
  reteach_snippet: string;
  expected_time_seconds: number;
  hints: any;
  created_at: Date;
}

interface ItemsTable {
  id: string;
  knowledge_point_id: string;
  type: string;
  prompt: any;
  rubric: any;
  difficulty: number;
  time_estimate_ms: number;
  randomization: any | null;
  encompassing_targets: any;
  created_at: Date;
}

interface StudentTopicStatesTable {
  student_id: string;
  topic_id: string;
  stability: number;
  strength: number;
  rep_num: number;
  due_at: Date;
  last_seen_at: Date | null;
  avg_latency_ms: number | null;
  speed_factor: number;
  struggling_flag: boolean;
  overdue_days: number;
  easiness: number | null;
  created_at: Date;
  updated_at: Date;
}

interface EvidenceEventsTable {
  id: string;
  student_id: string;
  topic_id: string;
  knowledge_point_id: string | null;
  item_id: string | null;
  task_id: string | null;
  result: "correct" | "incorrect" | "partial" | "skipped";
  latency_ms: number;
  hints_used: number;
  input_payload: any | null;
  confidence: number | null;
  created_at: Date;
}

interface StudentStatsTable {
  student_id: string;
  total_xp: number;
  current_streak: number;
  longest_streak: number;
  total_minutes: number;
  topics_completed: number;
  speed_drills_completed: number;
  last_active_at: Date | null;
  weekly_xp: any;
  updated_at: Date;
}
